//MAINCATEGORY
export const CREATE_MAINCATEGORY = "CREATE_MAINCATEGORY"
export const CREATE_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED"
export const GET_MAINCATEGORY = "CREATE_MAINCATEGORY"
export const GET_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED"
export const UPDATE_MAINCATEGORY = "CREATE_MAINCATEGORY"
export const UPDATE_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED"
export const DELETE_MAINCATEGORY = "CREATE_MAINCATEGORY"
export const DELETE_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED"